version: "3.8"
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    expose:
      - "5432"
  pgadmin:
    build: ./pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: joshua@zombie.local
      PGADMIN_DEFAULT_PASSWORD: joshua
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db